### ISSUE TITLE
在android7.0上经常报这错误是为啥呢

### ISSUE THREAD

**Issue by luyangliu616** [aohanyao/NoCacheViewPager#1]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.Rect android.graphics.drawable.Drawable.getBounds()' on a null object reference
	at android.text.style.DynamicDrawableSpan.getSize(DynamicDrawableSpan.java:78)
	at android.text.MeasuredText.addStyleRun(MeasuredText.java:238)
	at android.text.StaticLayout.generate(StaticLayout.java:727)
	at android.text.DynamicLayout.reflow(DynamicLayout.java:300)
	at android.text.DynamicLayout.<init>(DynamicLayout.java:175)
	at android.widget.TextView.makeSingleLayout(TextView.java:7219)
	at android.widget.TextView.makeNewLayout(TextView.java:7117)
	at android.widget.TextView.onMeasure(TextView.java:7471)
	at android.view.View.measure(View.java:19956)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6145)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1485)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:775)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:657)
	at android.view.View.measure(View.java:19956)
	at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1330)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.widget.ScrollView.onMeasure(ScrollView.java:352)
	at android.view.View.measure(View.java:19956)
	at com.pujia8.app.ui.listview.NoCacheViewPager.onMeasure(NoCacheViewPager.java:908)
	at android.view.View.measure(View.java:19956)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6145)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1485)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:775)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:657)
	at android.view.View.measure(View.java:19956)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
	at android.view.View.measure(View.java:19956)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6145)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1485)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:775)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:657)
	at android.view.View.measure(View.java:19956)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
	at android.view.View.measure(View.java:19956)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6145)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:19956)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6145)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1485)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:775)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:657)
	at android.view.View.measure(View.java:19956)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6145)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:729)
	at android.view.View.measure(View.java:19956)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2434)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1480)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1739)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1364)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6757)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:923)
	at android.view.Choreographer.doCallbacks(Choreographer.java:735)
	at android.view.Choreographer.doFrame(Choreographer.java:667)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:909)
	at android.os.Handler.handleCallback(Handler.java:755)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6524)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

**Comment by aohanyao** [comment]
没有吧，这应该不是外层ViewPager的错误。这个只是把错误抛出到这里。  另外我一直在用，7.0也在用。没什么问题。

**Comment by luyangliu616** [comment]
哦 我仔细看一下吧 主要是我这友盟统计爆这错误的都是7.0手机
